version: "3"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST}:${DB_PORT}:5432"

volumes:
  db-data:
